# Generated by Django 5.0.14 on 2025-11-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_places',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.place'),
        ),
    ]
